site_name: WEM Rules
site_url: https://enercloud-poc.github.io/wem-rules-prototype/
custom_dir: /
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/lightning-bolt
    favicon: material/lightning-bolt
  features:
    - content.tooltips
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - content.tabs.link
    - announce.dismiss
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
extra:
  version:
    provider: mike
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2022 EnerCloud Consulting. All rights reserved. 
